# Generated by Django 4.2.4 on 2023-08-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_is_registered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_registered',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
