# Generated by Django 4.2.4 on 2023-08-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('eleve', 'Eleve'), ('enseignant', 'Enseignant'), ('admin', 'Administrateur')], max_length=20, null=True),
        ),
    ]
