# Generated by Django 4.2.4 on 2023-08-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoirs', '0002_remove_projectmodule_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodule',
            name='period_date',
            field=models.DateField(),
        ),
    ]
