# Generated by Django 4.2.4 on 2023-08-20 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devoirs', '0004_remove_projectmodule_assigned_to_classe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodule',
            name='ELeves',
        ),
        migrations.RemoveField(
            model_name='projectmodule',
            name='period_date',
        ),
        migrations.RemoveField(
            model_name='projectmodule',
            name='period_time',
        ),
        migrations.AddField(
            model_name='projectmodule',
            name='Student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to='devoirs.student'),
        ),
        migrations.AddField(
            model_name='projectmodule',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='eLeves',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmodule',
            name='subject',
            field=models.TextField(),
        ),
    ]
