# Generated by Django 4.2.4 on 2023-08-20 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devoirs', '0005_remove_projectmodule_eleves_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='enseignant',
        ),
        migrations.RemoveField(
            model_name='student',
            name='eLeves',
        ),
        migrations.RemoveField(
            model_name='student',
            name='eleve',
        ),
        migrations.RemoveField(
            model_name='projectmodule',
            name='Student',
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.DeleteModel(
            name='Enseignant',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
