# Generated by Django 4.2.4 on 2023-08-23 19:53

import devoirs.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
 


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devoirs', '0006_remove_enseignant_enseignant_remove_student_eleves_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmodule',
            name='file',
        ),
        migrations.RemoveField(
            model_name='projectmodule',
            name='is_submitted',
        ),
        migrations.AddField(
            model_name='projectmodule',
            name='project_file',
            field=models.FileField(null=True, upload_to=devoirs.models.file_path_project),
        ),
        migrations.CreateModel(
            name='Submit_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_file', models.FileField(null=True, upload_to=devoirs.models.file_path_sbmt)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_project', to='devoirs.projectmodule')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='projectmodule',
            name='submitted',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_project', to='devoirs.submit_file'),
        ),
    ]
