# Generated by Django 4.2.4 on 2023-08-24 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devoirs', '0007_remove_projectmodule_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodule',
            name='submitted',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_project', to='devoirs.submit_file'),
        ),
    ]
