# Generated by Django 4.2.4 on 2023-08-25 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devoirs', '0008_alter_projectmodule_submitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmodule',
            name='Enseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmodule',
            name='assigned_to_eleve',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_eleve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectmodule',
            name='submitted',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_project', to='devoirs.submit_file'),
        ),
        migrations.AlterField(
            model_name='submit_file',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_project', to='devoirs.projectmodule'),
        ),
        migrations.AlterField(
            model_name='submit_file',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
