# Generated by Django 4.2.4 on 2023-08-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devoirs', '0009_alter_matiere_enseignant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodule',
            old_name='Enseignant',
            new_name='enseignant',
        ),
    ]
