# Generated by Django 4.2.4 on 2023-08-15 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('classe_name', models.CharField(max_length=100)),
                ('eleves', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL)),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes_assigned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('matiere_name', models.CharField(max_length=100)),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matieres_assigned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('eleve', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eleve', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('file', models.FileField(null=True, upload_to='projects/')),
                ('status', models.CharField(choices=[('in_progress', 'En cours'), ('submitted', 'Soumis'), ('evaluated', 'Évalué')], default='in_progress', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period_date', models.TimeField()),
                ('period_time', models.TimeField(null=True)),
                ('end_at', models.DateTimeField()),
                ('Enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_assigned', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='devoirs.classes')),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='devoirs.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enseignant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
